
import type { Metadata } from "next";

import "./globals.css";
import{ThemeProvider} from "@/components/theme-provider"






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
       <ThemeProvider>
      <body>
       
       
            {/* <HeaderCustom></HeaderCustom> */}
            <main>
              {children}
              
              </main>
              {/* <FooterCustom></FooterCustom> */}
          
         
        
        
      </body>
          </ThemeProvider>
    </html>
  );
}
