
import type { Metadata } from "next";

import "./globals.css";
import{ThemeProvider} from "@/components/theme/theme-provider"






export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ThemeProvider >
      <body>
            <main  >
              {children}
              
              </main>
        
        
      </body>
          </ThemeProvider>
    </html>
  );
}
